### ISSUE TITLE
Uncaught TypeError: Cannot read property 'statusCode' of undefined

### ISSUE THREAD

**Issue by junewunder** [ddavison/kinetic#14]
[Enter steps to reproduce below:]
1. open favicon.ico
2. upload to imgur

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: [kinetic](https://github.com/ddavison/kinetic) package, v0.2.5
### Stack Trace

Uncaught TypeError: Cannot read property 'statusCode' of undefined

```
At /Users/JacobWunder/.atom/packages/kinetic/lib/kinetic-module.coffee:123

TypeError: Cannot read property 'statusCode' of undefined
  at Request._callback (/Users/JacobWunder/.atom/packages/kinetic/lib/kinetic-module.coffee:123:53)
  at self.callback (/Users/JacobWunder/.atom/packages/kinetic/node_modules/request/request.js:121:22)
  at Request.emit (events.js:116:17)
  at ClientRequest.self.clientErrorHandler (/Users/JacobWunder/.atom/packages/kinetic/node_modules/request/request.js:230:10)
  at ClientRequest.emit (events.js:116:17)
  at TLSSocket.socketErrorListener (_http_client.js:273:9)
  at TLSSocket.emit (events.js:138:20)
  at net.js:452:14
  at process._tickCallback (node.js:366:11)

```
### Commands

```
     -6:51.5 editor:newline (atom-text-editor.editor)
     -6:51.1 core:save (atom-text-editor.editor)
  2x -6:49.9 core:backspace (atom-text-editor.editor)
  3x -6:48.0 core:move-down (atom-text-editor.editor)
     -6:44.5 core:undo (atom-text-editor.editor)
     -6:12.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-solarized-light-syntax.theme-solarized-light-ui)
     -1:09.9 settings-view:open (atom-text-editor.editor)
     -1:05.3 core:confirm (atom-text-editor.editor.mini)
     -0:27.6 command-palette:toggle (atom-text-editor.editor)
     -0:19.3 core:move-down (atom-text-editor.editor.mini)
     -0:18.4 core:confirm (atom-text-editor.editor.mini)
     -0:18.4 kinetic:upload-to-Imgur (atom-text-editor.editor)
     -0:02.5 command-palette:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:00.9 core:move-down (atom-text-editor.editor.mini)
     -0:00.6 core:confirm (atom-text-editor.editor.mini)
     -0:00.6 kinetic:upload-to-Imgur (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "atom-html-preview"
    ],
    "themes": [
      "solarized-light-ui",
      "solarized-light-syntax"
    ],
    "projectHome": "/Users/JacobWunder/Documents/",
    "audioBeep": false
  }
}
```
### Installed Packages

``` coffee
# User
achievements, v0.7.0
autocomplete-css, v0.4.0
autocomplete-html, v0.3.0
autocomplete-plus, v2.4.2
autocomplete-plus-jedi, v0.0.8
autocomplete-snippets, v1.0.1
kinetic, v0.2.5
minimap, v4.6.0
project-manager, v1.15.5
solarized-light-ui, v0.1.0
terminal-status, v1.3.5

# Dev
No dev packages
```

**Comment by ddavison** [comment]
Thanks for reporting this.  I'll look into it as soon as i can!

**Comment by junewunder** [comment]
no prob :+1:
